### ISSUE TITLE
license 校验结果 -5 

### ISSUE THREAD

**Issue by satan31415** [zhengzhuang96/rtmp_tencent_live#2]
大佬好:
(安卓平台)点击开始直播按钮会报
I/ContentValues(19079): 开始直播
I/b       (19079): liteav_api startPusher com.tencent.rtmp.b@71aa07b
I/isAssetFileExists(19079): TXLiveSDK.licence not exist
E/LicenceCheck(19079): downloadLicense, mUrl is empty, ignore!
I/ContentValues(19079): startRTMPPush: license 校验结果-5
I/ContentValues(19079): startRTMPPush: license 校验失败
美颜那些功能都能正常
我在官网下的安卓demo,确认过 licenseUrl, licenseKey, rtmpURL 这三个参数是可以推流成功的,
这个项目的 example 进去替换掉 licenseUrl, licenseKey, rtmpURL 也是同样的错误
不知道是不是除了配置上面三个参数,还有其他细节需要注意的

**Comment by satan31415** [comment]
大佬好:
安卓平台找到原因了
初始化的时候 腾讯那个框架会去下载 TXLiveSDK.licence 这个文件, 但是下载需要权限好像(不是原生开发不太懂)
反正会报 No Network Security Config specified, using platform default 
然后使用一个默认的 appid: 1302315621
我在安卓加了
 <uses-permission android:name="android.permission.INTERNET"/>
<uses-permission android:name="android.permission.MOUNT_UNMOUNT_FILESYSTEMS"/>

android:usesCleartextTraffic="true"
不知道哪个起作用, 反正就是能下载到那个文件,可以正常使用了
![image](https://user-images.githubusercontent.com/7278892/90096076-f7ad0180-dd64-11ea-93da-0103295f7d54.png)

**Comment by satan31415** [comment]
还有 License 没过期也可能会刷新, 我遇到睡了一觉起来 Key,	LicenseUrl 可能不一样了

**Comment by zhengzhuangpro** [comment]
License 没过期也可能会刷新, 这是什么意思，Key, LicenseUrl 是写在代码里面的啊，怎么会变呢

**Comment by satan31415** [comment]
我昨天写的 demo 申请的 License , 但是今天早上接着弄的时候,登上腾讯云管理后台, 发现和昨天不一样的, 我可以肯定是不一样的, 因为我重新替换过

**Comment by satan31415** [comment]
过期时间我设置成到月底,这几天我在注意下,看还会不会出现这样的问题

**Comment by satan31415** [comment]
不好意思我错了, 我在早上改了控制台的包名导致的

**Comment by softmaxs** [comment]
@satan31415 你好请教你一个问题，如何才能运行成功该项目？
运行项目时会报以下错误！麻烦邦看一下！
I/testArr ( 5963): 获取数据
W/Native-LiteAV( 5963): load library txffmpeg from system path 
W/Native-LiteAV( 5963): load library : java.lang.UnsatisfiedLinkError: dlopen failed: library "libtxffmpeg.so" not found
W/Native-LiteAV( 5963): load library txffmpeg false
W/Native-LiteAV( 5963): load library traeimp-rtmp from system path 
W/Native-LiteAV( 5963): load library : java.lang.UnsatisfiedLinkError: dlopen failed: library "libtraeimp-rtmp.so" not found
W/Native-LiteAV( 5963): load library traeimp-rtmp false
W/Native-LiteAV( 5963): load library liteavsdk from system path 
W/Native-LiteAV( 5963): load library : java.lang.UnsatisfiedLinkError: dlopen failed: library "libliteavsdk.so" not found

**Comment by softmaxs** [comment]
@satan31415 或者指点下启动运行流程
