### ISSUE TITLE
项目打包失败

### ISSUE THREAD

**Issue by kxr224** [zhengzhuang96/rtmp_tencent_live#8]
项目可以正常运行和开发
但是在我执行flutter build apk的时候出现了一个错误
![image](https://user-images.githubusercontent.com/28681083/108319178-f4a33a00-71fb-11eb-9d40-0f58667b5a32.png)
问题产生的原因可能是因为依赖冲突了，我在网上查了好多都没有找到好的办法。
后来我把GitHub上的案例运行了一下，经过测试发现只要加上video_play的依赖就会出现类似的问题
其他的都没有修改，只是增加了这个依赖
![image](https://user-images.githubusercontent.com/28681083/108319824-ed306080-71fc-11eb-91fd-29f4b0df3004.png)
再次打包的时候会出现这个问题
![image](https://user-images.githubusercontent.com/28681083/108319855-f9b4b900-71fc-11eb-9ad8-3989321bd2cd.png)
请问，关于这个问题，有没有办法解决一下，感谢🙏

**Comment by zhengzhuangpro** [comment]
插件冲突

**Comment by kxr224** [comment]
嗯嗯，我通过jar包引入的方式解决了这个问题
